### ISSUE TITLE
Wordform or "word form"?

### ISSUE THREAD

**Issue by componavt** [componavt/dictorpus#3]
Page title is [Wordforms](http://dictorpus.krc.karelia.ru/en/dict/wordform?search_dialect=26), but the [dialect list table](http://dictorpus.krc.karelia.ru/en/dict/dialect?lang_id=&limit_num=40) contains the column titled "Word forms".
English Wiktionary contains the article [wordform](https://en.wiktionary.org/wiki/wordform).

**Comment by lunata** [comment]
done.
